sybase_ase_orm:
    connections:
        default: '%env(resolve:DATABASE_URL)%'
    
    entity_managers:
        default:
            connection: default
            mappings:
                App:
                    type: attribute
                    dir: '%kernel.project_dir%/src/Entity'
                    prefix: 'App\Entity'
    
    default_connection: default
    default_entity_manager: default